const HtmlWebpackPlugin = require("html-webpack-plugin");

function createPages(template, filename, chunks) {
  return new HtmlWebpackPlugin({
    template: template,
    filename: filename,
    chunks: chunks,
  });
}

const htmlPages = [
  createPages("./src/index.html", "./index.html", ["index"]),
  createPages("./src/pages/about.html", "./pages/about.html", ["index"]),
  createPages("./src/pages/search.html", "./pages/search.html", ["index", "search"]),
  createPages("./src/pages/test.html", "./pages/test.html", ["index"]),
  createPages("./src/pages/category.html", "./pages/category.html", ["index", "search"]),
  createPages("./src/pages/test/test1.html", "./pages/test/test1.html", ["index", "test"]),
  createPages("./src/pages/test/test2.html", "./pages/test/test2.html", ["index", "test2"]),
  createPages("./src/pages/test/test3.html", "./pages/test/test3.html", ["index", "test3"]),
  createPages("./src/pages/category/it.html", "./pages/category/it.html", ["index",]),
  createPages("./src/pages/category/it.html", "./pages/category/data-analyst.html", ["index",]),
  createPages("./src/pages/category/site-administrator.html", "./pages/category/site-administrator.html", ["index",]),
  createPages("./src/pages/category/bi-analyst.html", "./pages/category/bi-analyst.html", ["index",]),
  createPages("./src/pages/category/web-designer.html", "./pages/category/web-designer.html", ["index",]),
  createPages("./src/pages/category/game-developer.html", "./pages/category/game-developer.html", ["index",]),
  createPages("./src/pages/category/data-scientist.html", "./pages/category/data-scientist.html", ["index",]),
  createPages("./src/pages/category/devOps-engineer.html", "./pages/category/devOps-engineer.html", ["index",]),
  createPages("./src/pages/category/cybersecurity-specialists.html", "./pages/category/cybersecurity-specialists.html", ["index",]),
  createPages("./src/pages/category/motion-designer.html", "./pages/category/motion-designer.html", ["index",]),
  createPages("./src/pages/category/product-manager.html", "./pages/category/product-manager.html", ["index",]),
  createPages("./src/pages/category/brand-manager.html", "./pages/category/brand-manager.html", ["index",]),
  createPages("./src/pages/category/content-marketer.html", "./pages/category/content-marketer.html", ["index",]),
  createPages("./src/pages/category/copywriter.html", "./pages/category/copywriter.html", ["index",]),
  createPages("./src/pages/category/digital-marketer.html", "./pages/category/digital-marketer.html", ["index",]),
  createPages("./src/pages/category/email-marketer.html", "./pages/category/email-marketer.html", ["index",]),
  createPages("./src/pages/category/marketer.html", "./pages/category/marketer.html", ["index",]),
  createPages("./src/pages/category/marketing.html", "./pages/category/marketing.html", ["index",]),
  createPages("./src/pages/category/pr-manager.html", "./pages/category/pr-manager.html", ["index",]),
  createPages("./src/pages/category/SMM-specialist.html", "./pages/category/SMM-specialist.html", ["index",]),
  createPages("./src/pages/category/traffic-manager.html", "./pages/category/traffic-manager.html", ["index",]),
  createPages("./src/pages/category/composer.html", "./pages/category/composer.html", ["index",]),
  createPages("./src/pages/category/costume-designer.html", "./pages/category/costume-designer.html", ["index",]),
  createPages("./src/pages/category/creative-industries.html", "./pages/category/creative-industries.html", ["index",]),
  createPages("./src/pages/category/creative-producer.html", "./pages/category/creative-producer.html", ["index",]),
  createPages("./src/pages/category/editor.html", "./pages/category/editor.html", ["index",]),
  createPages("./src/pages/category/graphic-designer.html", "./pages/category/graphic-designer.html", ["index",]),
  createPages("./src/pages/category/musician.html", "./pages/category/musician.html", ["index",]),
  createPages("./src/pages/category/photographer.html", "./pages/category/photographer.html", ["index",]),
  createPages("./src/pages/category/videographer.html", "./pages/category/videographer.html", ["index",]),
  createPages("./src/pages/category/Artist.html", "./pages/category/Artist.html", ["index",]),
  createPages("./src/pages/category/clinical-psychologist.html", "./pages/category/clinical-psychologist.html", ["index",]),
  createPages("./src/pages/category/forensic-expert.html", "./pages/category/forensic-expert.html", ["index",]),
  createPages("./src/pages/category/medical-lab-technician.html", "./pages/category/medical-lab-technician.html", ["index",]),
  createPages("./src/pages/category/medicine.html", "./pages/category/medicine.html", ["index",]),
  createPages("./src/pages/category/nurse.html", "./pages/category/nurse.html", ["index",]),
  createPages("./src/pages/category/oncologist.html", "./pages/category/oncologist.html", ["index",]),
  createPages("./src/pages/category/paramedic.html", "./pages/category/paramedic.html", ["index",]),
  createPages("./src/pages/category/pediatrician.html", "./pages/category/pediatrician.html", ["index",]),
  createPages("./src/pages/category/pharmacist.html", "./pages/category/pharmacist.html", ["index",]),
  createPages("./src/pages/category/surgeon.html", "./pages/category/surgeon.html", ["index",]),
  createPages("./src/pages/category/general-practitioner.html", "./pages/category/general-practitioner.html", ["index",]),
  createPages("./src/pages/category/finance.html", "./pages/category/finance.html", ["index",]),
  createPages("./src/pages/category/fintech-specialist.html", "./pages/category/fintech-specialist.html", ["index",]),
  createPages("./src/pages/category/compliance-specialist.html", "./pages/category/compliance-specialist.html", ["index",]),
  createPages("./src/pages/category/actuary.html", "./pages/category/actuary.html", ["index",]),
  createPages("./src/pages/category/economist.html", "./pages/category/economist.html", ["index",]),
  createPages("./src/pages/category/trader.html", "./pages/category/trader.html", ["index",]),
  createPages("./src/pages/category/tax-consultant.html", "./pages/category/tax-consultant.html", ["index",]),
  createPages("./src/pages/category/risk-management-specialist.html", "./pages/category/risk-management-specialist.html", ["index",]),
  createPages("./src/pages/category/underwriter.html", "./pages/category/underwriter.html", ["index",]),
  createPages("./src/pages/category/Meteorologist.html", "./pages/category/Meteorologist.html", ["index",]),
  createPages("./src/pages/category/Geophysicist.html", "./pages/category/Geophysicist.html", ["index",]),
  createPages("./src/pages/category/Cryptographer.html", "./pages/category/Cryptographer.html", ["index",]),
  createPages("./src/pages/category/Technologist.html", "./pages/category/Technologist.html", ["index",]),
  createPages("./src/pages/category/Chemical.html", "./pages/category/Chemical.html", ["index",]),
  createPages("./src/pages/category/Astrophysicist.html", "./pages/category/Astrophysicist.html", ["index",]),
  createPages("./src/pages/category/Physicist.html", "./pages/category/Physicist.html", ["index",]),
  createPages("./src/pages/category/Quantum-Engineer.html", "./pages/category/Quantum-Engineer.html", ["index",]),
  createPages("./src/pages/category/Research-Fellow.html", "./pages/category/Research-Fellow.html", ["index",]),
  createPages("./src/pages/category/Bioinformatician.html", "./pages/category/Bioinformatician.html", ["index",]),
  createPages("./src/pages/category/Research-Engineer.html", "./pages/category/Research-Engineer.html", ["index",]),
  createPages("./src/pages/category/Research-Scientist.html", "./pages/category/Research-Scientist.html", ["index",]),
  createPages("./src/pages/category/accurate.html", "./pages/category/accurate.html", ["index",]),
  createPages("./src/pages/category/Biologist.html", "./pages/category/Biologist.html", ["index",]),
  createPages("./src/pages/category/Ecologist.html", "./pages/category/Ecologist.html", ["index",]),
  createPages("./src/pages/category/Geographer.html", "./pages/category/Geographer.html", ["index",]),
  createPages("./src/pages/category/Geologist.html", "./pages/category/Geologist.html", ["index",]),
  createPages("./src/pages/category/Hydrologist.html", "./pages/category/Hydrologist.html", ["index",]),
  createPages("./src/pages/category/Oceanographer.html", "./pages/category/Oceanographer.html", ["index",]),
  createPages("./src/pages/category/Soil Scientist.html", "./pages/category/Soil Scientist.html", ["index",]),
  createPages("./src/pages/category/Volcanologist.html", "./pages/category/Volcanologist.html", ["index",]),
  createPages("./src/pages/category/Seismologist.html", "./pages/category/Seismologist.html", ["index",]),
  createPages("./src/pages/category/Astronomer.html", "./pages/category/Astronomer.html", ["index",]),
  createPages("./src/pages/category/Biotechnologist.html", "./pages/category/Biotechnologist.html", ["index",]),
  createPages("./src/pages/category/humanitarian.html", "./pages/category/humanitarian.html", ["index",]),
  createPages("./src/pages/category/education.html", "./pages/category/education.html", ["index",]),
  createPages("./src/pages/category/ecology.html", "./pages/category/ecology.html", ["index",]),
  createPages("./src/pages/category/constraction.html", "./pages/category/constraction.html", ["index",]),
  createPages("./src/pages/category/Foreman.html", "./pages/category/Foreman.html", ["index",]),
  createPages("./src/pages/category/Design Engineer.html", "./pages/category/Design Engineer.html", ["index",]),
  createPages("./src/pages/category/Estimator.html", "./pages/category/Estimator.html", ["index",]),
  createPages("./src/pages/category/Finisher.html", "./pages/category/Finisher.html", ["index",]),
  createPages("./src/pages/category/credit-analyst.html", "./pages/category/credit-analyst.html", ["index",]),
  createPages("./src/pages/category/M&A-specialist.html", "./pages/category/M&A-specialist.html", ["index",]),
  createPages("./src/pages/category/treasurer.html", "./pages/category/treasurer.html", ["index",]),
  createPages("./src/pages/category/financial-controller.html", "./pages/category/financial-controller.html", ["index",]),
  createPages("./src/pages/category/accountant.html", "./pages/category/accountant.html", ["index",]),
  createPages("./src/pages/category/auditor.html", "./pages/category/auditor.html", ["index",]),
  createPages("./src/pages/category/financial-analyst.html", "./pages/category/financial-analyst.html", ["index",]),
  createPages("./src/pages/category/finance.html", "./pages/category/finance.html", ["index",]),
  createPages("./src/styleguide.html", "./styleguide.html", ["styleguide", "index"]),
  createPages("./src/pages/search/search1.html", "./pages/search/search1.html", ["index", "search"]),
  createPages("./src/pages/search/trends1.html", "./pages/search/trends1.html", ["index", "search"]),
  createPages("./src/pages/search/trends2.html", "./pages/search/trends2.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini1.html", "./pages/search/trends-mini1.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini2.html", "./pages/search/trends-mini2.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini3.html", "./pages/search/trends-mini3.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini4.html", "./pages/search/trends-mini4.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini5.html", "./pages/search/trends-mini5.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini6.html", "./pages/search/trends-mini6.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini7.html", "./pages/search/trends-mini7.html", ["index", "search"]),
  createPages("./src/pages/search/trends-mini8.html", "./pages/search/trends-mini8.html", ["index", "search"]),

];

module.exports = htmlPages;
